name: Pull from GitHub

on: push

jobs:
  checkout:
    runs-on: ubuntu-latest
    container: 
      image: smartbear/ready-api-soapui-testrunner
      volumes:
        [~/project:/project,~/reports:/reports,~/extensions:/ext]
      env:
        LICENSE_SERVER: "127.0.0.1:1099"
        COMMAND_LINE: "-f/%reports% '-RJUnit-Style HTML Report' -FHTML '-EDefault environment' '/%project%/api-test.yaml'"
    steps:
      - uses: actions/checkout@v3
        with: 
          path: '~/'
      - name: Check for dockerenv file
        run: ls /project && ls /reports && ls /extensions